#!/bin/bash

# Slackware build script for Visual Studio Code Insiders
# It repackages the official Microsoft Visual Studio Code Insiders binary
# distribution for Linux.
#
# Copyright 2025 Branislav Anovic
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

set -e
set -u

DOWNLOAD_URL="https://code.visualstudio.com/sha/download?build=insider&os=linux-x64"
PRGNAM=vscode-insiders
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}
VERSION=${VISUAL_STUDIO_CODE_VERSION:-} # Passed from the calling script

# Determine version if not passed, but try to not download the file, still need network call for headers though:
if [ -z "$VERSION" ]; then
    VERSION=$(wget --spider --server-response "$DOWNLOAD_URL" 2>&1 | grep -i Content-Disposition | sed -En 's/^.*code-insider-x64-([0-9]+)\.tar\.gz.*$/\1/p')
fi

if [ -z "$VERSION" ]; then
    echo "Error: VERSION not set, unable to determine version" >&2
    exit 1
fi

if [ -z "${ARCH:-}" ]; then
    case "$( uname -m )" in
        i?86) ARCH=i586 ;;
        arm*) ARCH=arm ;;
        *) ARCH=$( uname -m ) ;;
    esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME:-}" ]; then
    echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
    exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
wget -q -c --content-disposition $DOWNLOAD_URL # Preserve original filename
tar xvf $TMP/code-insider-x64-$VERSION.tar.gz
cd VSCode-linux-x64
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

mkdir -p $PKG/opt/$PRGNAM $PKG/usr/bin
mv ./* $PKG/opt/$PRGNAM

# Clean up
rm -f $TMP/code-insider-x64-$VERSION.tar.gz
rmdir $TMP/VSCode-linux-x64

mkdir -p $PKG/usr/share/applications
cp $CWD/$PRGNAM.desktop $PKG/usr/share/applications
cp $CWD/$PRGNAM-url-handler.desktop $PKG/usr/share/applications

mkdir -p $PKG/usr/share/icons/hicolor/1024x1024/apps
cp $PKG/opt/$PRGNAM/resources/app/resources/linux/code.png $PKG/usr/share/icons/hicolor/1024x1024/apps

(
    cd $PKG/usr/bin
    ln -s /opt/$PRGNAM/bin/code-insiders .
)

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
